# Form implementation generated from reading ui file 'search-programm_interface.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(538, 463)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.search_chats = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.search_chats.setGeometry(QtCore.QRect(10, 10, 511, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_chats.sizePolicy().hasHeightForWidth())
        self.search_chats.setSizePolicy(sizePolicy)
        self.search_chats.setStyleSheet("border: None;\n"
"padding: 5px 5px 5px 5px;")
        self.search_chats.setObjectName("search_chats")
        self.nick_name = QtWidgets.QLabel(parent=self.centralwidget)
        self.nick_name.setGeometry(QtCore.QRect(10, 50, 91, 27))
        self.nick_name.setStyleSheet("font-size: 20px;")
        self.nick_name.setScaledContents(False)
        self.nick_name.setObjectName("nick_name")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 90, 511, 361))
        self.tabWidget.setToolTipDuration(0)
        self.tabWidget.setObjectName("tabWidget")
        self.freand_chats = QtWidgets.QWidget()
        self.freand_chats.setToolTipDuration(0)
        self.freand_chats.setObjectName("freand_chats")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.freand_chats)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.freand_list = QtWidgets.QListWidget(parent=self.freand_chats)
        self.freand_list.setStyleSheet("font-size: 15px;")
        self.freand_list.setObjectName("all_list")
        self.horizontalLayout.addWidget(self.freand_list)
        self.tabWidget.addTab(self.freand_chats, "")
        self.all_chats = QtWidgets.QWidget()
        self.all_chats.setObjectName("all_chats")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.all_chats)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.all_list = QtWidgets.QListWidget(parent=self.all_chats)
        self.all_list.setObjectName("freand_list")
        self.horizontalLayout_2.addWidget(self.all_list)
        self.tabWidget.addTab(self.all_chats, "")
        #MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tetridanoh"))
        self.nick_name.setText(_translate("MainWindow", "NickName"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.freand_chats), _translate("MainWindow", "Freand Chats"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.all_chats), _translate("MainWindow", "All Chats"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
